version: "3"
services:
  approved-npo-data:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: approved-npo-data-image
    container_name: approved-npo-data-container
    tty: true
